"""Internal runtime defaults that are intentionally not user-configurable."""

DELIVERY_POLL_INTERVAL_SECONDS = 1.0
DELIVERY_CONCURRENCY = 8
TELEGRAM_MIN_REQUEST_INTERVAL_SECONDS = 0.05
DELIVERY_MAX_ATTEMPTS = 8
POSTGRES_POOL_SIZE = 10
POSTGRES_MAX_OVERFLOW = 10
POSTGRES_POOL_TIMEOUT_SECONDS = 30.0
POSTGRES_POOL_RECYCLE_SECONDS = 1800

API_RATE_LIMIT_WINDOW_SECONDS = 60.0
API_AUTH_FAILURE_LIMIT = 10
API_AUTH_FAILURE_WINDOW_SECONDS = 60.0
API_OPERATOR_TELEGRAM_ID = 0

REMNAWAVE_TIMEOUT_SECONDS = 5.0
REMNAWAVE_RECONCILE_DELAY_SECONDS = 10.0

NOTIFICATION_WEBHOOK_TIMEOUT_SECONDS = 5.0
NOTIFICATION_WEBHOOK_MAX_ATTEMPTS = 8
NOTIFICATION_WEBHOOK_POLL_INTERVAL_SECONDS = 1.0
NOTIFICATION_WEBHOOK_CONCURRENCY = 4

RECONCILIATION_CONCURRENCY = 4
METRICS_DATABASE_CACHE_TTL_SECONDS = 30.0
